version: '3.4'
services:
  learning-chinese-video-fe:
    image: learning-chinese-video-fe
    container_name: learning-chinese-video-fe
    build:
      context: ./Clients/LearningChineseVideo
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4900:3000
    restart: always

  learning-chinese-video-api-v2:
    image: learning-chinese-video-api-v2
    container_name: learning-chinese-video-api-v2
    build:
      context: ./api/LearningVideoApi.v2
      dockerfile: Dockerfile
    volumes:
      - ./uploads:/LearningVideoApi.v2/uploads
    ports:
      - 7700:7700
    restart: always
 
  

